server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/you_db
    username: username
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/you_db
    user: user
    password: password
    locations: src/main/resources/db/migration/
  cloud:
    aws:
      credentials:
        access-key: you access-key
        secret-key: you secret-key
      region:
        static: ru-central1
      cloudwatch:
        endpoint: https://storage.yandexcloud.net
      buckets:
        default: you backet
  files:
    directories:
      uploads:
        local: src/main/resources/uploads

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: ilyap

uploads:
  filePath: src/main/resources/uploads
  fileMaxSize: 10240
  memMaxSize: 10240
