server:
  port: 8080

spring:
  r2dbc:
    url: ############################
    username: #########
    password: #########
  flyway:
    url: #######################
    user: ############################
    password: ############################
    locations: ############################
  cloud:
    aws:
      credentials:
        access-key: ############
        secret-key: ############
      region:
        static: ############################
      cloudwatch:
        endpoint: ############################
      buckets:
        default: ###################
  files:
    directories:
      uploads:
        local: ############################

jwt:
  password:
    encoder:
      secret: #############################
      iteration: 64
      keylength: 256
  secret: ###################################
  expiration: 3600
  issuer: ilyap

uploads:
  filePath: src/main/resources/uploads
  fileMaxSize: 10240
  memMaxSize: 10240
