server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/restapireactive
    username: root
    password: 228228
  flyway:
    url: jdbc:mysql://localhost:3306/restapireactive
    user: root
    password: 228228
    locations: classpath:db/migration

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: ilyap

aws:



uploads:
  filePath: classpath:/uploads
  fileMaxSize: 10240
  memMaxSize: 10240